version: 2
registries:
  npm-registry-npm-fontawesome-com:
    type: npm-registry
    url: https://npm.fontawesome.com
    token: "${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: gatsby
    versions:
    - 2.32.0
    - 2.32.7
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3
    - 3.0.4
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-plugin-sass
    versions:
    - 3.1.0
    - 3.2.0
    - 4.0.0
    - 4.0.1
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 3.0.0
    - 3.0.1
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.2.0
    - 3.2.1
    - 3.3.0
    - 3.3.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-transformer-remark
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-remark-images
    versions:
    - 4.0.0
    - 4.1.0
    - 4.1.1
    - 4.2.0
    - 5.0.0
  - dependency-name: gatsby-remark-responsive-iframe
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-plugin-offline
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-typography
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-remark-prismjs
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
    - 5.0.0
  - dependency-name: gatsby-remark-copy-linked-files
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-plugin-react-helmet
    versions:
    - 4.0.0
    - 4.1.0
    - 4.2.0
    - 4.3.0
  - dependency-name: gatsby-plugin-feed
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-remark-smartypants
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 4.0.0
  - dependency-name: gatsby-plugin-sitemap
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
    - 8.2.0
  - dependency-name: "@graphql-codegen/typescript"
    versions:
    - 1.21.1
    - 1.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: react-dom
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
  - dependency-name: lighthouse-batch
    versions:
    - 7.0.0
  registries:
  - npm-registry-npm-fontawesome-com
