---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: node:8
    environment:
      GITHUB_PRIVATE_SSH:
        from_secret: GITHUB_PRIVATE_SSH
    commands:
      - yarn config set registry https://my-registry.dokku.coreyja.com
      - yarn install --frozen --verbose
      - yarn test
  # - name: deploy
  #   image: node:8
  #   environment:
  #     AWS_ACCESS_KEY_ID:
  #       from_secret: AWS_ACCESS_KEY_ID
  #     AWS_SECRET_ACCESS_KEY:
  #       from_secret: AWS_SECRET_ACCESS_KEY
  #     AWS_BUCKET:
  #       from_secret: AWS_BUCKET
  #     AWS_DISTRIBUTION_ID:
  #       from_secret: AWS_DISTRIBUTION_ID
  #   commands:
  #     - yarn install
  #     - yarn build
  #   when:
  #     # branch:
  #     #   - master
  #     event:
  #       - push
---
kind: signature
hmac: db357a16afe0bd9efe98d93ff6811ffcb0f124c6a0c401e571396fbb233ab123

...
