---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: restore
  pull: true
  image: coreyja/rust-cache:yarn
  settings:
    aws_access_key_id:
      from_secret: CACHE_AWS_ACCESS_KEY_ID
    aws_secret_access_key:
      from_secret: CACHE_AWS_SECRET_ACCESS_KEY
    cache_bucket: cache.dokku.coreyja
    cache_download: true

- name: install
  image: node:8
  commands:
  - "echo \"//my-registry.dokku.coreyja.com/:_authToken=$NPM_AUTH_TOKEN\" >> .npmrc"
  - "echo \"//npm.fontawesome.com/:_authToken=$FONTAWESOME_AUTH_TOKEN\" >> .npmrc"
  - yarn config set cache-folder "$(pwd)/.cache/yarn"
  - yarn install --frozen
  environment:
    FONTAWESOME_AUTH_TOKEN:
      from_secret: FONTAWESOME_AUTH_TOKEN
    NPM_AUTH_TOKEN:
      from_secret: NPM_AUTH_TOKEN

- name: test
  image: node:8
  commands:
  - yarn install --frozen
  - yarn test

- name: build
  image: node:8
  commands:
  - yarn install --frozen
  - yarn build
  environment:
    AWS_BUCKET:
      from_secret: AWS_BUCKET

- name: deploy
  image: node:8
  commands:
  - yarn install --frozen
  - yarn deploy
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: AWS_ACCESS_KEY_ID
    AWS_BUCKET:
      from_secret: AWS_BUCKET
    AWS_DISTRIBUTION_ID:
      from_secret: AWS_DISTRIBUTION_ID
    AWS_SECRET_ACCESS_KEY:
      from_secret: AWS_SECRET_ACCESS_KEY
  when:
    branch:
    - master
    event:
    - push

- name: rebuild
  image: coreyja/rust-cache:yarn
  settings:
    aws_access_key_id:
      from_secret: CACHE_AWS_ACCESS_KEY_ID
    aws_secret_access_key:
      from_secret: CACHE_AWS_SECRET_ACCESS_KEY
    cache_bucket: cache.dokku.coreyja

---
kind: signature
hmac: 6589b82293ed2871e04c30c9e9f88915694512519ac117889a667553ea746191

...
