---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: install
    image: node:8
    environment:
      NPM_AUTH_TOKEN:
        from_secret: NPM_AUTH_TOKEN
    commands:
      - yarn config set registry https://my-registry.dokku.coreyja.com
      - echo "registry=https://my-registry.dokku.coreyja.com/" > ~/.npmrc
      - echo "//my-registry.dokku.coreyja.com/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
      - echo "always-auth=true" >> ~/.npmrc
      - yarn install --frozen
  - name: test
    image: node:8
    commands:
      - yarn install --frozen
      - yarn test
  - name: build
    image: node:8
    environment:
      AWS_BUCKET: coreyja-blog-staging
        # from_secret: AWS_BUCKET
    commands:
      - yarn install --frozen
      - yarn build
  - name: deploy
    image: node:8
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_BUCKET: coreyja-blog-staging
        # from_secret: AWS_BUCKET
      AWS_DISTRIBUTION_ID:
        from_secret: AWS_DISTRIBUTION_ID
    commands:
      - yarn install --frozen
      - yarn deploy
    when:
      # branch:
      #   - master
      event:
        - push
---
kind: signature
hmac: 21a3ace1d099fdcb3803c95b0dd760c88f87107799f957f4b7047157ef33e23b

...
