---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: restore
    image: plugins/s3-cache
    settings:
      pull: true
      restore: true
      root: cache.dokku.coreyja
      access_key:
        from_secret: CACHE_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: CACHE_AWS_SECRET_ACCESS_KEY
  - name: test
    image: ruby:2.3.3
    environment:
      RAILS_ENV: test
    commands:
      - bundle config --local path "vendor/bundle"
      - bundle install --frozen --jobs 5 --retry 5
      - bundle exec rubocop
      - bundle exec scss-lint
  - name: deploy
    image: timbru31/ruby-node:2.3
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_BUCKET:
        from_secret: AWS_BUCKET
      AWS_DISTRIBUTION_ID:
        from_secret: AWS_DISTRIBUTION_ID
    commands:
      - bundle config --local path "vendor/bundle"
      - bundle install --frozen --jobs 5 --retry 5
      - ./script/deploy.sh
    when:
      branch:
        - master
      event:
        - push
  - name: rebuild
    image: plugins/s3-cache
    settings:
      pull: true
      rebuild: true
      root: cache.dokku.coreyja
      access_key:
        from_secret: CACHE_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: CACHE_AWS_SECRET_ACCESS_KEY
      mount:
        - vendor/bundle
  - name: flush-cache
    image: plugins/s3-cache
    settings:
      flush: true
      flush_age: 30
      root: cache.dokku.coreyja
      access_key:
        from_secret: CACHE_AWS_ACCESS_KEY_ID
      secret_key:
        from_secret: CACHE_AWS_SECRET_ACCESS_KEY
---
kind: signature
hmac: 8ad8d21fa02ca8c3aa6f18cb4398bf6f381eff4969c9d071b2166ce41f60b2c0

...
