---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: restore
    image: coreyja/rust-cache
    settings:
      pull: true
      cache_download: true
      cache_bucket: cache.dokku.coreyja
      aws_access_key:
        from_secret: CACHE_AWS_ACCESS_KEY_ID
      aws_secret_key:
        from_secret: CACHE_AWS_SECRET_ACCESS_KEY
  - name: test
    image: ruby:2.3.3
    environment:
      RAILS_ENV: test
    commands:
      - bundle config --local path "vendor/bundle"
      - bundle install --frozen --jobs 5 --retry 5
      - bundle exec rubocop
      - bundle exec scss-lint
  - name: deploy
    image: timbru31/ruby-node:2.3
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_BUCKET:
        from_secret: AWS_BUCKET
      AWS_DISTRIBUTION_ID:
        from_secret: AWS_DISTRIBUTION_ID
    commands:
      - bundle config --local path "vendor/bundle"
      - bundle install --frozen --jobs 5 --retry 5
      - ./script/deploy.sh
    when:
      branch:
        - master
      event:
        - push
  - name: rebuild
    image: coreyja/rust-cache
    settings:
      cache_download: true
      cache_bucket: cache.dokku.coreyja
      aws_access_key:
        from_secret: CACHE_AWS_ACCESS_KEY_ID
      aws_secret_key:
        from_secret: CACHE_AWS_SECRET_ACCESS_KEY
---
kind: signature
hmac: caa7585df87d39d5b1104c86ae9b8efe556b2039ff6c0b82ea91070ebb64647d

...
