---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: node:8
    environment:
      GITHUB_PRIVATE_SSH:
        from_secret: GITHUB_PRIVATE_SSH
    commands:
      - mkdir $HOME/.ssh
      - echo "$GITHUB_PRIVATE_SSH" > /root/.ssh/id_rsa
      - chmod 400 /root/.ssh/id_rsa
      - echo "Host github.com\n\tIdentityFile /root/.ssh/id_rsa\n" >> /root/.ssh/config
      - ssh-keyscan github.com >> /root/.ssh/known_hosts
      - yarn install --frozen --verbose
      - yarn test
  # - name: deploy
  #   image: node:8
  #   environment:
  #     AWS_ACCESS_KEY_ID:
  #       from_secret: AWS_ACCESS_KEY_ID
  #     AWS_SECRET_ACCESS_KEY:
  #       from_secret: AWS_SECRET_ACCESS_KEY
  #     AWS_BUCKET:
  #       from_secret: AWS_BUCKET
  #     AWS_DISTRIBUTION_ID:
  #       from_secret: AWS_DISTRIBUTION_ID
  #   commands:
  #     - yarn install
  #     - yarn build
  #   when:
  #     # branch:
  #     #   - master
  #     event:
  #       - push
---
kind: signature
hmac: f3a62ce0a226ddbc122001b295085d4b44b2aea815db1fe79e31a6017fee7926

...
