---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: node:8
    environment:
      NPM_AUTH_TOKEN:
        from_secret: NPM_AUTH_TOKEN
    commands:
      - yarn config set registry https://my-registry.dokku.coreyja.com
      - echo "registry=https://my-registry.dokku.coreyja.com/" > ~/.npmrc
      - echo "//my-registry.dokku.coreyja.com/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
      - echo "always-auth=true" >> ~/.npmrc
      - yarn install --frozen
      - yarn test
  - name: deploy
    image: node:8
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_BUCKET: coreyja-blog-staging
        # from_secret: AWS_BUCKET
      AWS_DISTRIBUTION_ID:
        from_secret: AWS_DISTRIBUTION_ID
    commands:
      - yarn install
      - yarn build
    when:
      # branch:
      #   - master
      event:
        - push
---
kind: signature
hmac: 37d3f638737f5c8d1a51539213a0ef4fbcbf692211eac4e3c2207732824598f8

...
