version: 2.1
commands:
  yarn-install:
    steps:
      - run: "echo \"//npm.fontawesome.com/:_authToken=$FONTAWESOME_AUTH_TOKEN\" >> .npmrc"
      - run: "echo \"//npm.pkg.github.com/:_authToken=$GITHUB_PACKAGE_TOKEN\" >> .npmrc"
      - run: yarn install --frozen
jobs:
  test:
    parallelism: 1
    docker:
      - image: circleci/node:14.0.0
    steps:
      - checkout
      - yarn-install
      - run: yarn test
  deploy:
    parallelism: 1
    docker:
      - image: circleci/node:14.0.0
    steps:
      - checkout
      - yarn-install
      - run: yarn build
      - run: yarn deploy
workflows:
  version: 2.1
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
